// autogenerated by AnimGen v.1.0, do not modify
#ifndef ani_expl_h___
#define ani_expl_h___

#include "core/common/com_misc.h"
#include "resources.h"
#include "ext/primitives/r_primitives.h"
#include "ext/primitives/r_sheet_sprite.h"


class res::ResourcesPool;
typedef r::SheetSprite CharacterSprite;


class ani_expl
{
public:
  enum eAnimations
  {
      aExp = 0,
      aCount = 1
  };
  static u32 GetFrame( eAnimations anim, u32 frame, u8 dir );
  static u32 GetFrame( eAnimations anim, f32 time,  u8 dir );
  static u32 GetNFrames( eAnimations anim );
  static u32 GetNDirs  ( eAnimations anim );
  static const CharacterSprite* CreateSprite( r::Render& r, res::ResourcesPool& rpool );


private:
  static const u32 sFrameCounts[aCount];
  static const u32 sDirs[aCount];
  static const u32 sFrameCountX = 12;
  static const u32 sFrameCountY = 1;
  static const u32 sSpriteOnscreenWidth = 96;
  static const u32 sSpriteOnscreenHeight = 96;
  static const u32 sFrameCount = 12;
  static const u32 sPivotX = 48;
  static const u32 sPivotY = 48;
};


#endif // #ifndef ani_expl_h___
