// autogenerated by ResScan v.1.0.1, do not modify
#ifndef RESOURCES_H
#define RESOURCES_H
#include "core/common/com_misc.h"

#define RES_8BIT_BMFC 0
#define RES_8BIT_FNT 1
#define RES_8BIT_0_PNG 2
#define RES_MAINMENU_SPR 3
#define RES_MAINMENU_0_PNG 4
#define RES_MUSMAINMENU_MP3 5

#endif // RESOURCES_H
