// autogenerated by ResScan v.1.0.1, do not modify
#ifndef RESOURCES_H
#define RESOURCES_H
#include "core/common/com_misc.h"

#define RES_8BIT_BMFC 0
#define RES_8BIT_FNT 1
#define RES_8BIT_0_PNG 2
#define RES_MAINMENU_SPR 3
#define RES_MAINMENU_0_PNG 4
#define RES_MUSMAINMENU_MP3 5
#define RES_SFXEXPLODE1_WAV 6
#define RES_SFXEXPLODE2_WAV 7
#define RES_SFXEXPLODE3_WAV 8
#define RES_SFXHIT_WAV 9
#define RES_SFXMENUAPPLY_WAV 10
#define RES_SFXMENUSELECT_WAV 11
#define RES_SFXPLASMAHIT_WAV 12
#define RES_SFXREFILLENERGYSTEP_WAV 13
#define RES_SFXSHOOT_WAV 14

#endif // RESOURCES_H
