// autogenerated by ResScan v.1.0.1, do not modify
#include "resources.h"
#include "core/res/res_base.h"
NAMESPACE_BEGIN(res)
ResourceTableEntry m_gameresources[] =
{
  {ResID(RES_8BIT_BMFC),"8bit.bmfc"},
  {ResID(RES_8BIT_FNT),"8bit.fnt"},
  {ResID(RES_8BIT_0_PNG),"8bit_0.png"},
  {ResID(RES_MAINMENU_SPR),"mainmenu.spr"},
  {ResID(RES_MAINMENU_0_PNG),"mainmenu_0.png"},
  {ResID(RES_MUSMAINMENU_MP3),"MusMainMenu.mp3"},
};

u32 m_ngameresources = sizeof(m_gameresources) / sizeof(m_gameresources[0]);
NAMESPACE_END(res)
