// autogenerated by SheetSprGen v.1.0, do not modify
#ifndef sheet_mainmenu_h___
#define sheet_mainmenu_h___

namespace r {
  class Render;
  class SheetSprite;
} // namespace r

namespace res {
  class ResourcesPool;
} // namespace res

class mainmenu
{
public:
  enum eFrame
  {
      MainMenuBackground = 0,
      aCount = 1
  };
  static const r::SheetSprite* GetSprite( r::Render& r, res::ResourcesPool& rpool );
};

#endif // #ifndef sheet_mainmenu_h___
