// autogenerated by SheetSprGen v.1.0, do not modify
#ifndef sheet_gameplay_h___
#define sheet_gameplay_h___

namespace r {
  class Render;
  class SheetSprite;
} // namespace r

namespace res {
  class ResourcesPool;
} // namespace res

class gameplay
{
public:
  enum eFrame
  {
      Asteroid1 = 0,
      Asteroid2 = 1,
      Asteroid3 = 2,
      AsteroidBigChunk1 = 3,
      AsteroidBigChunk2 = 4,
      AsteroidBigChunk3 = 5,
      AsteroidBigChunk4 = 6,
      AsteroidMediumChunk1 = 7,
      AsteroidMediumChunk2 = 8,
      AsteroidMediumChunk3 = 9,
      AsteroidMediumChunk4 = 10,
      AsteroidSmallChunk1 = 11,
      AsteroidSmallChunk2 = 12,
      AsteroidSmallChunk3 = 13,
      AsteroidSmallChunk4 = 14,
      Gun = 15,
      LabelP1 = 16,
      LabelP2 = 17,
      LabelVictory = 18,
      PickupEnergy = 19,
      Planet1 = 20,
      Planet2 = 21,
      Planet3 = 22,
      Planet4 = 23,
      Planet5 = 24,
      Planet6 = 25,
      PlasmaBullet = 26,
      Ship1 = 27,
      Ship2 = 28,
      ShipImpactCircle = 29,
      ShipShield = 30,
      SpaceBackgroundChunk1 = 31,
      SpaceBackgroundChunk2 = 32,
      SpaceBackgroundChunk3 = 33,
      SpaceBackgroundChunk4 = 34,
      StationEmpty = 35,
      StationFull = 36,
      aCount = 37
  };
  static const r::SheetSprite* GetSprite( r::Render& r, res::ResourcesPool& rpool );
};

#endif // #ifndef sheet_gameplay_h___
